config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms' => 'terms#index'
  get '/faq' => 'common_questions#index'
  get '/users' => 'users#index'
  get '/about' => 'about#index'
  get '/projects' => 'projects#index'
  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only:[:create]
    end
    resources :memberships
  end
    resources :tracker_api
end

app/models/membership.rb
class Membership < ActiveRecord::Base
belongs_to :project
belongs_to :user

validates :user, uniqueness: {scope: :project_id, message: 'has already been added to this project'}
validates :user, presence: true




  def membership_content(membership)
    if membership.roles == 2
      "Owner"
    else
      "Member"
    end
  end


end

app/controllers/memberships_controller.rb
class MembershipsController < PrivateController
  helper_method :ensure_last_owner
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :find_membership, except: [:index, :create]
  before_action :logged_in_users_without_access, only:[:edit, :update, :destroy]
  before_action :verify_membership, except: [:new, :create, :index]
  before_action :verify_owner, only: [:edit, :update]
  before_action :verify_owner_or_membership, only: [:destroy]
  before_action :ensure_last_owner, only: [:update, :destroy]
  before_action :ensure_current_user


  def index
    @membership = @project.memberships.new
  end

  def create
    @membership = @project.memberships.new(membership_params)
    if @membership.save
      flash[:notice] = "#{@membership.user.full_name} was successfully added"
      redirect_to project_memberships_path(@project.id)
    else
      render :index
    end
  end

  def update
    membership = @project.memberships.find(params[:id])
    if membership.update(membership_params)
      redirect_to project_memberships_path, notice: "#{membership.user.full_name} was successfully updated"
    else
      redirect_to project_memberships_path(@project)
    end
  end

  def destroy
    membership = Membership.find(params[:id])
    membership.destroy
    if current_user.id == membership.user_id
      flash[:notice] = "#{membership.user.full_name} was successfully deleted"
      redirect_to projects_path
    else
      flash[:notice] = "#{membership.user.full_name} was successfully deleted"
      redirect_to project_memberships_path
  end
end


private

  def membership_params
    if current_user.admin
      params.require(:membership).permit(:roles, :user_id, :project_id)
    else
      params.require(:membership).permit(:roles, :user_id, :project_id)
    end
  end

  def find_membership
    @membership = Membership.find(params[:id])
  end

  def logged_in_users_without_access
    unless current_user.memberships.pluck(:project_id).include?(@project.id) || current_user.admin
      flash[:error] = "You do not have access"
      redirect_to project_path(@project)
    end
  end

  def ensure_last_owner
    membership = @project.memberships.find(params[:id])
      if membership.present?
        if membership.roles == 2 && @project.memberships.where(roles: 2).count == 1
          flash[:error] = "Projects must have at least one owner"
          redirect_to project_memberships_path(@project)
        end
      end
    end

  def ensure_current_user
    unless current_user
      session[:previous_page] = request.fullpath
      flash[:error] = "You must sign in"
      redirect_to sign_in_path
    end
  end

   end

app/views/memberships/index.html.haml
.container
  .page-header
    %h1 #{@project.name}: Manage Members
  %ol.breadcrumb
    %li
      =link_to "Projects", projects_path
    %li
      =link_to "#{@project.name}", project_path(@project)
    %li.active Memberships

  .row
    .col-md-7
      -if @membership.errors.any?
        .alert.alert-danger
          .h3
            =pluralize(@membership.errors.count, "error")
            ="prohibited this from from being saved:"
          -@membership.errors.full_messages.each do |message|
            %ul
              %li
                = message

  .row
    .col-md-7
      - if current_user.membership_owner_or_admin(@project)
        = form_for [@project, @membership], html: { class: "form-inline"} do |f|
          .well
            .form-group
              = f.collection_select :user_id, User.all, :id, :full_name, {prompt: "Please select a user.."}, {class: "form-control"}
            .form-group
              = f.select(:roles, [["Member", 1], ["Owner", 2]], {}, {class: 'form-control'})
            .form-group
              = f.submit "Add New Member", {class: "btn btn-primary"}

  .row
    .col-md-7
      %table.table
        %tbody
          - @project.memberships.each do |membership|
            - if membership.id.present? && membership.id.present?
              %tr
                = form_for [@project, membership], html: {class: "form-inline"} do |f|
                  %td
                    = link_to membership.user.full_name, user_path(membership.user)
                  %td
                    - if current_user.membership_owner_or_admin(@project)
                      = f.select(:roles, [["Member", 1], ["Owner", 2]], {}, {class: 'form-control'})
                      %td
                        = f.submit "update", {class: "btn btn-primary"}
                        -if membership.roles == 2 && @project.memberships.where(roles: 2).count == 1
                          %td
                            = 'You are the last owner'
                        -else
                          %td
                            = link_to ' ', project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"
                    - else
                    %td
                      = membership.membership_content(membership)
                      - if current_user.id == membership.user_id
                        .pull-right
                          = link_to ' ', project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"