config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms' => 'terms#index'
  get '/faq' => 'common_questions#index'
  get '/users' => 'users#index'
  get '/about' => 'about#index'
  get '/projects' => 'projects#index'
  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only:[:create]
    end
    resources :memberships
  end
    resources :tracker_api
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :description, presence: true


  has_many :comments, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < PrivateController
  before_action :ensure_current_user
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :verify_membership

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:notice] = "Task was successfully created"
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def show
    @task = @project.tasks.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to project_task_path(@project, @task)
      flash[:notice] = "Task was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    task = @project.tasks.find(params[:id])
    task.destroy
    redirect_to project_tasks_path(@project), notice: "Task was successfully deleted"
  end

  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date, :project_id)
  end
  

  def ensure_current_user
    unless current_user
      session[:previous_page] = request.fullpath
      flash[:error] = "You must sign in"
      redirect_to sign_in_path
    end
  end
end

app/views/tasks/_form.html.haml
.container
= form_for [@project, @task], html: {class: "form-horizontal"} do |f|

  = render partial: "shared/errors", locals:{object: @task}

  .form-group
    = f.label :description, class: "col-md-2 control-label"
    .col-md-6
      = f.text_field :description, class: "form-control", placeholer:"Description"


  .form-group
    = f.label :due_date, class: "col-md-2 control-label"
    .col-md-3
      = f.date_field :due_date, class: "form-control", placeholer:"Due Date"

  -unless @task.new_record?
    .form-group
      .col-md-offset-2.col-md-6
        = f.check_box :complete
        = f.label :complete

  .form-group
    .col-md-offset-2.col-md-6
      = f.submit class: "btn btn-primary"
      = link_to "Cancel", project_tasks_path(@project), class: "btn btn-default"

app/views/tasks/edit.html.haml
.container
  .page-header
    %h1 Editing Tasks

  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li
      = link_to @project.name, project_path(@project)
    %li
      = link_to "Tasks", project_tasks_path
    %li.active Edit Task

  = render partial: "form"

app/views/tasks/index.html.haml
.container
  .page-header
    .pull-right
      = link_to 'New Task', new_project_task_path, class: "btn btn-info"
    %h1 Tasks for #{@project.name}

  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li
      = link_to @project.name, project_path(@project)
    %li.active Tasks

  %table.table
    %thead
      %tr
        %th Description
        %th Due On
        %th
    %tbody
      - @tasks.each do |task|

        %tr
          %td
            - if task.complete
              %u
                %s
                  = link_to task.description, project_task_path(@project, task)

            - else

              %u
                = link_to task.description, project_task_path(@project, task)
            .badge=task.comments.count
          %td
            - if task.due_date
              = task.due_date.strftime("%m/%d/%Y")
          %td
            .pull-right
              = link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-info"
              = link_to ' ', project_task_path(@project, task), method: :delete, class: "glyphicon glyphicon-remove"

app/views/tasks/new.html.haml
.container
  .page-header
    %h1 New Task

  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li
      = link_to @project.name, project_path(@project)
    %li
      = link_to "Tasks", project_tasks_path
    %li.active New Task
  = render partial:"form"

app/views/tasks/show.html.haml
.container
  .page-header
    .row
      .col-md-7
        %h1
          - if @task.complete == true
            %s
              = @task.description
          - else
            = @task.description

      .col-md-5
        .pull-right
          =  link_to "Edit", edit_project_task_path(@project, @task), class: "btn btn-info margin-top-button"

  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li
      = link_to @project.name, project_path(@project)
    %li
      = link_to "Tasks", project_tasks_path
    %li
      = @task.description

  .row
    .col-md-7
      - if @task.due_date
        Due on:
        = @task.due_date.strftime("%m/%d/%Y")

  %h2 Comments
  .comments
    - @task.comments.each do |comment|
      .row
        .col-md-3
          .row
            .col-md-12
              -unless User.where(id: comment.user_id) == []
                = link_to comment.user.full_name, user_path(comment.user)
              -else
                %p (deleted user)

          .row
            .col-md-12.txt-muted
              = time_ago_in_words(comment.created_at) + " ago"
        .col-md-9
          %p= comment.content
        %br

  = form_for [@project, @task, @comment], html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-offset-3.col-md-9
        = f.text_area :content, class: 'form-control'
    .form-group
      .col-md-offset-3.col-md-7
        = f.submit 'Add Comment', class: 'btn btn-primary'