config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/terms' => 'terms#index'
  get '/faq' => 'common_questions#index'
  get '/users' => 'users#index'
  get '/about' => 'about#index'
  get '/projects' => 'projects#index'
  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only:[:create]
    end
    resources :memberships
  end
    resources :tracker_api
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  has_many :users, through: :memberships, dependent: :destroy
  has_many :memberships, dependent: :destroy

  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < PrivateController

  before_action :ensure_current_user
  before_action :set_project, except: [:new, :create, :index]
  before_action :verify_membership, except: [:new, :create, :index]
  before_action :verify_owner, only: [:edit, :update, :delete]


  def index
    @projects = current_user.projects
    @project_admins = Project.all
    tracker_api = TrackerAPI.new
    if current_user.pivotal_tracker_token
      tracker_response = tracker_api.projects(current_user.pivotal_tracker_token)
      if tracker_response.is_a? Array
        @tracker_projects = tracker_response
      else
        @tracker_projects = []
        flash.now[:warning] = 'Invalid Token'
      end
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @user = current_user
    if @project.save
      flash[:notice] = "Project was created successfully"
        redirect_to project_tasks_path(@project)
      @project.memberships.create!(roles: 2, user_id: @user.id)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project)
      flash[:notice] = "Project was edited successfully"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: "The project has been successfully deleted"
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def ensure_current_user
    unless current_user
      flash[:error] = "You must sign in"
      redirect_to sign_in_path
    end
  end



end

app/views/projects/_form.html.haml
.container
= form_for @project, html: {class: "form-horizontal"} do |f|
  = render partial: "shared/errors", locals:{object: @project}
  .form-group
    = f.label :name, class: "col-md-2 control-label"
    .col-md-6
      = f.text_field :name, class: "form-control", placeholder: "Name"
  .form-group
    .col-md-offset-2.col-md-6
      = f.submit class: "btn btn-primary"
      = link_to "Cancel", projects_path, class: "btn btn-default"

app/views/projects/edit.html.haml
.container
  .page-header
    %h1 Edit Project
  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li
      = link_to @project.name, project_path(@project)
    %li.active
      = "Edit"
= render partial:"form"
  

app/views/projects/index.html.haml
.container
  %table.table
    .pull-right
      = link_to "New Project", new_project_path, class: "btn btn-info margin-top-button2"
    .page-header
      %h1 Projects
    %table.table
      %thead
        %tr
          %th
            %b Name
          %th
            %b Tasks
      %tbody
        - if current_user.admin
          - @project_admins.each do |project|
            %tr
              %td
                = link_to project.name, project_path(project)
              %td
                = link_to project.tasks.count, project_tasks_path(project, @task)

        - else
          - @projects.each do |project|
            %tr
              %td
                = link_to project.name, project_path(project)
              %td
                = link_to project.tasks.count, project_tasks_path(project, @task)
    -if current_user.pivotal_tracker_token
      %h1
        .page-header
          Pivotal Tracker Projects
      %table.table
        %thead
          %tr
            %th
              %b Name
          %tbody
            -@tracker_projects.each do |project|
              %tr
                %td
                  = link_to project[:name], tracker_api_path(project[:id], project_name: project[:name])

app/views/projects/new.html.haml
.container
  .page-header
    %h1 New Project
  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li.active
      = "New Project"  
= render partial:"form"

app/views/projects/show.html.haml
.container
  .page-header
    - if current_user.membership_owner_or_admin(@project)
      = link_to "Edit", edit_project_path, class: "btn btn-primary pull-right"
    %h1= @project.name

  %ol.breadcrumb
    %li
      = link_to "Projects", projects_path
    %li.active
      = @project.name

  - if @project.tasks.count == 1
    = link_to "#{@project.tasks.count} Task\n", project_tasks_path(@project)
  - else
    = link_to "#{@project.tasks.count} Tasks\n", project_tasks_path(@project)
  %br

  - if @project.memberships.count == 1
    = link_to "#{@project.memberships.count} Membership", project_memberships_path(@project)
  - else
    = link_to "#{@project.memberships.count} Memberships", project_memberships_path(@project)

  - if current_user.membership_owner_or_admin(@project)
    .well
      %h3 Delete Project
      %p
        = "Deleting this project will also delete #{pluralize(@project.memberships.count, 'membership')} #{pluralize(@project.tasks.count, 'task')}, and associated comments"
      %p
        = link_to "Delete", project_path(@project), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure you want to delete"}